# -*- coding: utf-8 -*-
"""tamAPP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X95F2M9D4jzItvg6zZNPFS5yQABwsa3J
"""

import streamlit as st
import joblib
import numpy as np
import os
def main():
    st.title("Miami Housing Prediction by Tanmay")

    # Example of using a relative path
    model_path = os.path.join(os.path.dirname(__file__), 'miami_housing_model')
    model = joblib.load(model_path)

    p1 = st.number_input("LATITUDE")
    p2 = st.number_input('LONGITUDE')

    p3 = st.number_input("LND_SQFOOT")
    p4 = st.number_input("TOT_LVG_AREA")
    p5 = st.number_input("SPEC_FEAT_VAL")

    p6 = st.number_input("RAIL_DIST")
    p7 = st.number_input("OCEAN_DIST")
    p8 = st.number_input("WATER_DIST")
    p9 = st.number_input("CNTR_DIST")
    p10 = st.number_input("SUBCNTR_DI")
    
    p11 = st.number_input("HWY_DIST")
    p12 = st.number_input("age")
    p13 = st.number_input("avno60plus")
    p14 = st.number_input("month_sold")
    p15 = st.number_input("structure_quality")


    # Debugging statements
    print(f"Inputs: {p1}, {p2}, {p3}, {p4}, {p5}, {p6}, {p7}, {p8}, {p9}, {p10}, {p11}, {p12} {p13}, {p14}, {p15}")
    input_data = np.array([[p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15]])
    print(f"Input data shape: {input_data.shape}")

    # Example result (replace with your prediction logic)
    if st.button("Best Price"):
        try:
            prediction = model.predict(input_data)
            st.balloons()
            st.success(f"Best Price for your dream home {round(prediction[0], 2)} US Dollars")
        except Exception as e:
            st.error(f"Error in prediction: {e}")

if __name__ == '__main__':
    main()
