# -*- coding: utf-8 -*-
"""tamAPP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X95F2M9D4jzItvg6zZNPFS5yQABwsa3J
"""

import streamlit as st
import joblib
import numpy as np
import os
def main():
    st.title("Miami Housing Prediction by Tanmay")

    # Example of using a relative path
    model_path = os.path.join(os.path.dirname(__file__), 'miami_housing_model')
    model = joblib.load(model_path)

    p1 = st.number_input("LATITUDE")
    p1 = st.number_input('LONGITUDE')

    p3 = st.number_input("LND_SQFOOT")
    p4 = st.number_input("TOT_LVG_AREA")
    p5 = st.number_input("SPEC_FEAT_VAL")

    p6 = st.number_input("Enter your region", 1,4)#"southwest":0, "southeast":1, "northwest":2, "northeast":3
    s3 = st.selectbox("Enter your region", ("Southwest", "Southeast", "Northwest", "Northeast"))
    if s2 == "Southwest":
        p6 = 0
    elif s2 == "Southeast":
        p6 = 1
    elif s3 == "Northwest":
        p6 = 2
    else:
        p6 = 3

    # Debugging statements
    print(f"Inputs: {p1}, {p2}, {p3}, {p4}, {p5}, {p6}")
    input_data = np.array([[p1, p2, p3, p4, p5, p6]])
    print(f"Input data shape: {input_data.shape}")

    # Example result (replace with your prediction logic)
    if st.button("Predict"):
        try:
            prediction = model.predict(input_data)
            st.balloons()
            st.success(f"Your insurance cost is {round(prediction[0], 2)} US Dollars")
        except Exception as e:
            st.error(f"Error in prediction: {e}")

if __name__ == '__main__':
    main()